site_url: https://wntic.github.io/segmentation-robustness-framework/
site_name: Segmentation Robustness Framework
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - User Guide: user_guide.md
  - Core Concepts:
    - Framework Concepts: concepts.md
    - Custom Components: custom_components.md
  # - Advanced Usage:
  #   - Advanced Usage: advanced_usage.md
  #   - API Reference: api_reference.md
  # - Reference:
  #   - Model Loaders: model_loaders.md
  #   - Configuration Guide: configuration_guide.md
  #   - Universal Configuration: universal_configuration_guide.md
  #   - Custom Datasets: custom_datasets_guide.md
  #   - Data Formats: data_formats_reference.md
  #   - Practical Example: practical_example.md