model:
  name: "FCN"
  encoder: "resnet101"
  weights: "coco_with_voc_labels"
  num_classes: 21
  device: "cuda"

attacks:
  - name: "FGSM"
    epsilon: [0.05, 0.125, 0.25]
  - name: "PGD"
    epsilon: [0.05, 0.125, 0.25]
    alpha: [0.007]
    steps: 40
    targeted: true
    target_label: 12

dataset:
  name: "PascalVOC"
  root: "../datasets/VOCdevkit/VOC2012/"
  split: "val"
  image_shape: [512, 376]
  max_images: 2

output:
  save_dir: "./runs/"
  save_images: true
