model:
  origin: torchvision
  name: DeepLabV3
  encoder: resnet50
  weights: coco_with_voc_labels  # or `default`
  num_classes: 21
  device: cuda

attacks:
  - name: FGSM
    epsilon: [0.01, 0.25, 0.5, 0.75, 1]

  - name: PGD
    epsilon: [0.01, 0.25, 0.5, 0.75, 1]
    alpha: [0.007]
    steps: 40
    targeted: false

  - name: TPGD
    epsilon: [0.01, 0.25, 0.5, 0.75, 1]
    alpha: [0.07]
    steps: 10

  - name: PGD
    epsilon: [0.01, 0.25, 0.5, 0.75, 1]
    alpha: [0.007]
    steps: 10
    targeted: true
    target_label: 15

  - name: RFGSM
    epsilon: [0.01, 0.25, 0.5, 0.75, 1]
    alpha: [0.07]
    steps: 10
    targeted: true
    target_label: 15

dataset:
  name: VOC
  root: path/to/VOCdevkit/VOC2012/
  split: val
  image_shape: [512, 376]
  max_images: 2
