model:
  name: "DeepLabV3"
  encoder: "resnet101"
  weights: "coco_with_voc_labels"
  num_classes: 21
  device: "cuda"

attacks:
  - name: "FGSM"
    epsilon: [0.05, 0.125, 0.25, 0.5, 0.66]
  - name: "PGD"
    epsilon: [0.05, 0.37, 0.5]
    alpha: [0.003, 0.007]
    steps: 40
    targeted: true
    target_label: 15

dataset:
  name: "PascalVOC"
  root: "path/to/VOCdevkit/VOC2012/"
  split: "val"
  image_shape: [512, 376]
  max_images: 100
